services:
  mysql:
    image: mysql:8.4
    container_name: gestion-congresos-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - gestion-congresos-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../gestion-congresos-backend
      dockerfile: Dockerfile

    container_name: gestion-congresos-backend

    restart: unless-stopped

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy
        
    environment:
      DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}

    networks:
      - gestion-congresos-network

  frontend:
    build:
      context: ../gestion-congresos-frontend
      dockerfile: Dockerfile

    container_name: gestion-congresos-frontend

    ports:
      - "5173:5173"

    volumes:
    - ../gestion-congresos-frontend:/app
    - /app/node_modules
    
    environment:
      CHOKIDAR_USEPOLLING: "true"

    depends_on:
      - backend

    networks:
      - gestion-congresos-network

volumes:
  mysql_data:

networks:
  gestion-congresos-network:
    driver: bridge
